name: Windows C++ CI

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup Visual Studio environment
      uses: ilammy/msvc-dev-cmd@v1.4.1
      with:
        arch: x64

    - name: Build Solution
      run: msbuild 270226unit-tests.sln /p:Configuration=Debug /p:Platform=x64

    - name: Run C++ tests with VSTest
      run: vstest.console.exe x64/debug/TEST_1.dll /Platform:x64 /Logger:trx /ResultsDirectory:TestResults

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ci-test-results
        path: TestResults/
